### ISSUE TITLE
[FeatureRequest]: Add Slicer Print time to JSON Resopnse

### ISSUE THREAD

**Issue by SirBramble** [dc42/RepRapFirmware#947]
### Is your feature request related to a problem? Please describe.

I've recently integrated my Printer (Duet 2 recently upgraded to Firmware 3.4.6) in to Home Assistant and am using the JSON response to get the current print times, temperatures, etc. from the current Print.

However the remaining print times based on file/filament/layer vary quite a lot and are inaccurate at the beginning to middle of a print.

### Describe the solution you propose.

It would be great if the print time based on the slicer, shown in the Printers 'Job/Status' page, would be included in the JSON response.

### Describe alternatives you've considered

I have not found a workaround so far.

### Provide any additional context or information.

![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/c92cd182-d241-4edd-a0eb-f0d96d1ef600)

I'm also a bit confused, because I found the parameter with the Object model plugin:
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/ed83f1b3-9368-4437-9e52-285569896e23)

But I'm also new to all of this, so if I'm just missing something obvious, help would be greatly appreciated.

**Comment by T3P3** [comment]
The slicer time left should be in the OM (e.g.: here):
https://github.com/Duet3D/RepRapFirmware/wiki/Object-Model-Documentation-Beta-&-RC#jobtimesleftslicer

But AFAIK the slicer needs to set the time.

**Comment by SirBramble** [comment]
Thanks for the quick reply.

I found it in the object model, but it isn't included in the JSON response (at least not as far as I can tell).

This is my current YAML config:
```
- platform: rest
    name: Duet Status
    resource: http://192.168.0.52/rr_status?type=3
    value_template: "{{ value_json.status }}"
    force_update: true
    json_attributes:
      - temps
      - currentLayer
      - fractionPrinted
      - printDuration
      - timesLeft
  - platform: template
    sensors:
      print_duration:
        friendly_name: "Time Printed"
        value_template: "{{ states.sensor.duet_status.attributes.printDuration // 60 }}"
        unit_of_measurement: "min"
      print_timeleft:
        friendly_name: "Est Time Left"
        value_template: "{{ states.sensor.duet_status.attributes.timesLeft.slicer // 60 }}"
        unit_of_measurement: "min"
```
"Time Printed" works, "EST Time Left" does not
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/a1b50891-f66c-4867-9d9e-b942570effb2)

Am I missing something here?

**Comment by dc42** [comment]
It works for me, using PrusaSlicer and RRF 3.5.0-rc.2+.
![image](https://github.com/Duet3D/RepRapFirmware/assets/2720876/2822dd6c-990d-42a9-a8b0-3a5b23cfa5bc)

**Comment by dc42** [comment]
If you are using the M408 response or the rr_status response, be aware those are legacy features. They will not be extended and they will be removed in a future version, perhaps as soon as RRF 3.6.0.

**Comment by SirBramble** [comment]
Ok, Interesting. I'm on 3.4.6 and got this response:
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/ad0fb92e-de72-4932-baf3-19a8a763363e)
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/1f6e2c41-c7f7-468b-890b-f1055cd2f62a)
Sorry for the bad picture, but I have no other way to show the values.

I only have file and filament.

For reference:
URL called: http://192.168.0.52/rr_status?type=3
Slicer: Cura V5.4.0
Showes up in the Interface:
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/8c9c823c-b3dd-43b3-a611-82bd4fd4bc3d)

Is there maybe a setting or config option I have to change?

**Comment by SirBramble** [comment]
Ok, so I got it working with the object model. Still need to port the rest of the parameters from rr_status, but at least it workes now.

@dc42 Thanks for the Help. The M408 gcode showed me in the right direction.

For anyone stumbling across this:
YAML config:
```
- platform: rest
    name: Duet Status
    resource: http://192.168.0.52/rr_status?type=3
    value_template: "{{ value_json.status }}"
    force_update: true
    json_attributes:
      - temps
      - currentLayer
      - fractionPrinted
      - printDuration
  - platform: rest
    name: Duet Status new
    resource: http://192.168.0.52/rr_model?key=job&flags=n
    value_template: "{{ value_json.key }}"
    json_attributes_path: "$.result"
    force_update: true
    json_attributes:
      - timesLeft
      - lastDuration
      - duration
  - platform: template
    sensors:
      head_temp_current:
        friendly_name: "Nozzle Temperature Current"
        value_template: "{{ states.sensor.duet_status.attributes.temps.current[1] }}"
        unit_of_measurement: "°C"
      head_temp_active:
        friendly_name: "Nozzle Temperature Active"
        value_template: "{{ states.sensor.duet_status.attributes.temps.tools.active[0][0] }}"
        unit_of_measurement: "°C"
      bed_temp_current:
        friendly_name: "Bed Temperature Current"
        value_template: "{{ states.sensor.duet_status.attributes.temps.current[0] }}"
        unit_of_measurement: "°C"
      bed_temp_active:
        friendly_name: "Bed Temperature Active"
        value_template: "{{ states.sensor.duet_status.attributes.temps.bed.active }}"
        unit_of_measurement: "°C"
      print_percentage:
        friendly_name: "Percentage Printed"
        value_template: "{{ states.sensor.duet_status.attributes.fractionPrinted }}"
        unit_of_measurement: "%"
      print_duration:
        friendly_name: "Time Printed"
        #value_template: "{{ states.sensor.duet_status_new.attributes.duration // 60.0|float(0.0)}}"
        value_template: "{{ state_attr('sensor.duet_status_new', 'duration')|int(0) // int(60) }}"
        unit_of_measurement: "min"
      print_timeleft:
        friendly_name: "Est Time Left"
        value_template: "{{ states.sensor.duet_status_new.attributes.timesLeft.slicer|int(0) // int(60)}}"
        unit_of_measurement: "min"

homeassistant:
  customize:
    sensor.duet_status:
      friendly_name: "3D Printer Status"
      icon: mdi:printer-3d

group:
  3dprinter:
    name: Ender5
    entities:
      - sensor.duet_status
      - sensor.duet_status_new
      - sensor.head_temp_current
      - sensor.head_temp_active
      - sensor.bed_temp_current
      - sensor.bed_temp_active
      - sensor.print_percentage
  3dprintstats:
```
Plugin for model browser (useful to look up parameter location):
![image](https://github.com/Duet3D/RepRapFirmware/assets/115991187/f02e547e-886a-49c5-bac6-00edf0f54599)

Useful links:
[https://github.com/Duet3D/RepRapFirmware/wiki/HTTP-requests#get-rr_model](https://github.com/Duet3D/RepRapFirmware/wiki/HTTP-requests#get-rr_model)
[https://docs.duet3d.com/User_manual/Reference/Gcodes](https://docs.duet3d.com/User_manual/Reference/Gcodes) (under M409)
[https://jsonviewer.stack.hu/](https://jsonviewer.stack.hu/) (useful for visualizing JSON response)
[http://LOCAL_IP_PRINTER/rr_model?key=job&flags=n](http://LOCAL_IP_PRINTER/rr_model?key=job&flags=n) (get objectModel/Job JSON response from browser)
